FROM eclipse-temurin:21-jdk AS build
WORKDIR /app
COPY Main.java Servidor.java Ordenacao.java Busca.java ./
RUN javac Main.java Servidor.java Ordenacao.java Busca.java

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app /app

EXPOSE 8002

CMD ["java", "Main"]